name: Lint

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  lint-makefile:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Validate Makefile
        run: make help
  lint-yaml:
    runs-on: ubuntu-24.04
    steps:
      - uses: actions/checkout@v4
      - name: Install yamllint
        run: pip install yamllint
      - name: Lint
        run: yamllint -d relaxed stacks/ .github/
